[bans]
multiple-versions = "warn"

[graph]
all-features = true

[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "Unicode-3.0",
]
confidence-threshold = 0.8

[[licenses.exceptions]]
crate = "webpki-roots"
allow = ["CDLA-Permissive-2.0", "MPL-2.0"]

[[licenses.clarify]]
crate = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]
