name: License Scanning

on:
  - push

jobs:
  fossa:
    # This job is only useful when run on upstream
    if: github.repository == 'nginx/ngx-rust' || github.event_name == 'workflow_dispatch'
    name: FOSSA scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run FOSSA scan and upload build data
        uses: fossas/fossa-action@3ebcea1862c6ffbd5cf1b4d0bd6b3fe7bd6f2cac # v1.7.0
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
